@extends('layouts.app')

@section('content')
<section class="post-hero"><div class="section-inner"><a href="{{ url('/blog') }}" class="post-back-link">← Kembali ke Blog</a><div class="post-hero-grid"><div><div class="post-meta-row"><p class="post-date"><span>{{ $post['date'] }}</span><span aria-hidden="true">·</span><span>{{ $post['read_time'] }}</span></p><span class="post-author"><span class="post-author-icon" aria-hidden="true">♙</span><span>PT Cipta Progresa Usaha</span></span></div><h1>{{ $post['title'] }}</h1><p class="post-excerpt">{{ $post['excerpt'] }}</p></div><div class="post-hero-image"><img src="{{ $post['image'] }}" alt="{{ $post['title'] }}"></div></div></div></section>

        <section class="post-section"><div class="section-inner"><div class="post-layout"><article class="post-content"><p class="post-intro">{{ $post['excerpt'] }}</p>@foreach($post['content'] as $paragraph)<p>{{ $paragraph }}</p>@endforeach<div class="post-callout"><span>Catatan CiptaProgresa</span><strong>Pengetahuan menjadi berarti ketika membantu organisasi mengambil langkah yang lebih baik.</strong></div><div class="post-share"><span>Bagikan artikel</span><a href="https://www.linkedin.com/sharing/share-offsite/?url={{ urlencode(url('/blog/'.$slug)) }}" target="_blank" rel="noopener">LinkedIn ↗</a><a href="https://wa.me/?text={{ urlencode($post['title'].' '.url('/blog/'.$slug)) }}" target="_blank" rel="noopener">WhatsApp ↗</a></div></article><aside class="related-sidebar"><p class="profile-overline">Baca berikutnya</p><h2>Artikel terkait</h2><div class="related-list">@foreach($related as $relatedSlug => $relatedPost)<a href="{{ url('/blog/'.$relatedSlug) }}" class="related-card"><img src="{{ $relatedPost['image'] }}" alt="{{ $relatedPost['title'] }}"><div><span>{{ $relatedPost['category'] }}</span><h3>{{ $relatedPost['title'] }}</h3><small>{{ $relatedPost['date'] }}</small></div></a>@endforeach</div></aside></div></div></section>

        <section class="blog-cta"><div class="section-inner"><div class="blog-cta-box"><div><p class="profile-overline">Belajar bersama kami</p><h2>Siap mengubah insight menjadi langkah berikutnya?</h2></div><a href="{{ url('/jadwal-pelatihan') }}" class="cp-hero-button">Lihat jadwal pelatihan <span>→</span></a></div></div></section>
@endsection
